---
 tasks file for master

  shell: kubeadm reset

- shell: kubeadm init --pod-network-cidr=10.32.0.0/12  --apiserver-advertise-address={{ ip_address }} --token=b0f7b8.8d1767876297d85c

- pause:
    minutes: 5
    
- file: 
    state: directory
    path: /root/.kube 

- copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

...
